rbac:
  readSecrets: true
master:
  initScripts:
    - |
      System.setProperty('org.apache.commons.jelly.tags.fmt.timeZone', 'America/Argentina/Buenos_Aires')
  JCasC:
    defaultConfig: false
    configScripts:
      jenkins-settings: |
        jenkins:
          crumbIssuer:
            standard:
              excludeClientIPFromCrumb: true
          globalNodeProperties:
          - envVars:
              env:
              - key: "GITHUB_URL"
                value: "https://github.com/jcontti"
              - key: "JENKINS_PIPELINES_PROJ"
                value: "k8s-cluster"
        unclassified:
          globalLibraries:
            libraries:
            - defaultVersion: "master"
              name: "jenkins-shared-library"
              retriever:
                modernSCM:
                  scm:
                    git:
                      credentialsId: "BBsvcAccnt"
                      remote: "https://github.com/jcontti/k8s-cluster.git"
                      traits:
                      - "gitBranchDiscovery"
        jobs:
        - script: >
            folder('devops') {
                displayName('Devops')
                description('Folder for Devops utils')
            }
        - script: >
            folder('devops/docker-images') {
                displayName('Docker images')
                description('Folder for Docker images')
            }
        - script: >
            pipelineJob('devops/docker-images/jenkins-lighthouse') {
              environmentVariables {
                keepBuildVariables(true)
                keepSystemVariables(true)
              }
              definition {
                cpsScm {
                  scm {
                    git {
                      remote {
                        url 'https://github.com/guipal/apiSampleJava.git'
                        credentials 'BBsvcAccnt'
                      }
                      branch 'master'
                      extensions {}
                    }
                  }
                  scriptPath 'pipelines/Test_Automation.groovy'
                }
              }
              logRotator {
                numToKeep(30)
                artifactNumToKeep(30)
              }
            }